# Generated by Django 5.2.8 on 2026-07-12 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField()),
                ('distance_from_origin_km', models.PositiveIntegerField(default=0)),
                ('arrival_offset_minutes', models.PositiveIntegerField(default=0, help_text='Minutes from trip departure time')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.route')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('route', 'sequence')},
            },
        ),
    ]
