# Generated by Django 5.2.8 on 2026-07-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_routestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
