# Generated by Django 5.2.8 on 2026-07-12 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_route_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seater_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sleeper_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('route_stop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fare', to='routes.routestop')),
            ],
        ),
    ]
