# Generated by Django 5.2.8 on 2026-07-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_stopfare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='fare',
        ),
    ]
