# Generated by Django 5.2.8 on 2026-07-12 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('deck', models.CharField(choices=[('LOWER', 'Lower'), ('UPPER', 'Upper')], default='LOWER', max_length=10)),
                ('seat_type', models.CharField(choices=[('SEATER', 'Seater'), ('SLEEPER', 'Sleeper')], max_length=10)),
                ('position', models.CharField(choices=[('WINDOW', 'Window'), ('AISLE', 'Aisle')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='buses.bus')),
            ],
            options={
                'unique_together': {('bus', 'seat_number')},
            },
        ),
    ]
