# Generated by Django 5.2.8 on 2026-07-12 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('buses', '0002_seat'),
        ('routes', '0005_remove_route_fare'),
        ('trips', '0002_remove_trip_arrival_time_remove_trip_available_seats_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='boarding_stop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boarding_bookings', to='routes.routestop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='dropping_stop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dropping_bookings', to='routes.routestop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='fare_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='buses.seat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.trip'),
        ),
        migrations.CreateModel(
            name='SeatHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boarding_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_holds', to='routes.routestop')),
                ('dropping_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropping_holds', to='routes.routestop')),
                ('held_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='buses.seat')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='trips.trip')),
            ],
        ),
    ]
