# Generated by Django 5.2.8 on 2026-07-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_seat_number_booking_boarding_stop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
