# Generated by Django 5.2.8 on 2026-07-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='price',
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
